### ISSUE TITLE
Solr instal

### ISSUE THREAD

**Issue by mmallejac** [timlegge/docker-foswiki#6]
Hello again,

Not being familiar yet with docker (learning !), I am wondering about the Solr install.

Should I use docker-compose with the solr docker image and combine it with your using docker-compose ? Or should it be installed within your docker image ?

Also which version of Solr should I use here ? The SolrPlugin page mention 5 or later : is the latest Solr image (8.3.0) fine ?

Many thanks !
Michel

**Comment by timlegge** [comment]
Hi

I will have to check my install tomorrow to be sure but I likely used something like:

sudo docker network create foswiki_net

sudo docker run --rm --network=foswiki_net --name docker-foswiki -idt -p 80:80 -p 443:443  -v foswiki_www:/var/www/foswiki:z -v nginx:/etc/nginx:z timlegge/docker-foswiki:v1.06

sudo docker run --rm --network=foswiki_net --name my_solr -d -P -idt -p 8983:8983 -v solr:/var/log/solr:z solr

That creates a new network that can be used between the containers.  At that point you can use my_solr as the host name in foswiki.

At this point you can copy the required  files from the foswiki volume to the solr volume

Version may be an issue as I forget off hand which solr version will work.

I will take a look at the install tonight to see if I can replicate it.  I was planning to document it anyway.

**Comment by mmallejac** [comment]
Many thanks, that is really helpful

Le mar. 12 nov. 2019 à 17:54, Timothy Legge <notifications@github.com> a
écrit :

**Comment by timlegge** [comment]
So, the schema in the foswiki configs does not work with version 8 so:

sudo docker run --rm --network=foswiki_net --name my_solr -d -P -idt -p 8983:8983 -v solr:/var/log/solr:z -v solr_data:/var/solr/data:z solr:7

Works
then:

cd /var/lib/docker/volumes/solr_data/_data/
cp -r ../../foswiki_www/_data/solr/cores .
mkdir configsets 
cd configsets
cp -r ../../../foswiki_www/_data/solr/configsets .

That should get you a semi working solr install

Note the docs say to link the directories but I forget what exactly I did

**Comment by timlegge** [comment]
sudo docker run --rm --network=foswiki_net --name my_solr -d -P -idt -p 8983:8983 -v solr:/var/log/solr:z -v solr_home:/opt/solr/server/solr:z solr:5

The above will get a working install after you copy the files in place and change the permissions

sudo docker stop my_solr
sudo docker run --rm --network=foswiki_net --name my_solr -d -P -idt -p 8983:8983 -v solr:/var/log/solr:z -v solr_home:/opt/solr/server/solr:z --user=root solr:5

docker exec -it my_solr /bin/sh
chown -R solr:solr /opt/solr/server/solr 
exit
sudo docker run --rm --network=foswiki_net --name my_solr -d -P -idt -p 8983:8983 -v solr:/var/log/solr:z -v solr_home:/opt/solr/server/solr:z solr:5

**Comment by timlegge** [comment]
I've made some progress on updating the solr configs for foswiki to support 6.6 of Solr in the attached file.  

sudo docker run --rm --network=foswiki_net --name my_solr -d -P -idt -p 8983:8983 -v solr_home6:/opt/solr/server/solr:z -v solr_home7:/var/solr solr:6

[solr6.6.6.tar.gz](https://github.com/timlegge/docker-foswiki/files/3839375/solr6.6.6.tar.gz)

Let me know if it works for you

**Comment by MichaelDaum** [comment]
Awesome. I'll have a look at it and merge it with the next upcoming changes.

**Comment by timlegge** [comment]
And for 7.7.2
[solr7.7.2.tar.gz](https://github.com/timlegge/docker-foswiki/files/3840910/solr7.7.2.tar.gz)

**Comment by timlegge** [comment]
Here is a command that seems to work well for solr.  It creates volumes for the logs, configsets and cores.  It also mounts the volume that the foswiki container uses.  Because of that the instructions to do symbolic links will work fine.

sudo docker run --rm --network foswiki-net --name my_solr -d -P \
-v solr_logs:/opt/solr/server/logs:z \
-v solr_configsets:/opt/solr/server/solr/configsets:z \
-v solr_foswiki:/opt/solr/server/solr/solr_foswiki:z \
-v foswiki_www:/var/www/foswiki:z \
-e GC_LOG_OPTS='' -e SOLR_LOG_LEVEL='WARN' -t solr:5

If you choose to use the update solr 6 or 7 configs from above use solr:6 or solr:7

**Comment by mmallejac** [comment]
I'll let you know. Many thanks !
I am trying to set up a docker-compose.yml, that will ease the setup I guess

**Comment by timlegge** [comment]
Hi

I was looking at docker-compose just today and I was thinking of how to
make it easier.  The setup itself is not that hard but docker-compose looks
like it could make it a one line command to start up both solr and
foswiki.  If you write something I can add it to the repo.  If not over the
next bit I will likely create one.

**Comment by mmallejac** [comment]
I've made some progress. I have a `docker-compose.yml` file which works fine, that reproduces the volumes and environment variables that you have described previously : 

I m using local port 8765 to access foswiki locally.

```
version: '3'

services:
  foswiki:
    image: timlegge/docker-foswiki
    container_name: foswiki
    depends_on:
      - solr
    ports:
      - 8765:80
    volumes:
      - solr_logs:/opt/solr/server/logs
      - solr_configsets:/opt/solr/server/solr/configsets
      - solr_foswiki:/opt/solr/server/solr/solr_foswiki
      - foswiki_www:/var/www/foswiki
    networks:
      - foswiki-network

  solr:
    image: solr:5
    container_name: solr
    # only to have access to solr console, delete in prodcution
    ports:
      - 8983:8983
    volumes:
      - solr_logs:/opt/solr/server/logs
      - solr_configsets:/opt/solr/server/solr/configsets
      - solr_foswiki:/opt/solr/server/solr/solr_foswiki
      - foswiki_www:/var/www/foswiki
    environment:
      - GC_LOG_OPTS=''
      - SOLR_LOG_LEVEL='WARN'
    networks:
      - foswiki-network

volumes:
  foswiki_www:
  solr_logs:
  solr_configsets:
  solr_foswiki:

networks:
  foswiki-network:

```

Then I run the following two commands (later will be included somehow in the compose file), and restart the solr container :

```
cd /opt/solr/server/solr/configsets   ; ln -s /var/www/foswiki/solr/configsets/foswiki_configs/ .
cd /opt/solr/server/solr/solr_foswiki ; ln -s /var/www/foswiki/solr/cores/foswiki/core.properties .
```

Most probably the second line of commands is not correct.  I see in the logs that the foswiki configset is read, but it crashes after that about the core : 

```
...
solr       | 1263 INFO  (main) [   ] o.a.s.c.CorePropertiesLocator Looking for core definitions underneath /opt/solr/server/solr
solr       | 1282 INFO  (main) [   ] o.a.s.c.CoreDescriptor Created CoreDescriptor: {name=foswiki, config=solrconfig.xml, transient=false, schema=schema.xml, loadOnStartup=true, configSetProperties=configsetprops.json, configSet=foswiki_configs, solr.autoSoftCommit.maxTime=6000, solr.autoCommit.maxTime=15000, dataDir=data/}
solr       | 1282 INFO  (main) [   ] o.a.s.c.CorePropertiesLocator Found core foswiki in /opt/solr/server/solr/solr_foswiki
solr       | 1282 INFO  (main) [   ] o.a.s.c.CorePropertiesLocator Found 1 core definitions
solr       | 1288 INFO  (coreLoadExecutor-6-thread-1) [   ] o.a.s.c.SolrResourceLoader new SolrResourceLoader for directory: '/opt/solr/server/solr/configsets/foswiki_configs'
solr       | 1289 INFO  (coreLoadExecutor-6-thread-1) [   ] o.a.s.c.SolrResourceLoader JNDI not configured for solr (NoInitialContextEx)
solr       | 1289 INFO  (coreLoadExecutor-6-thread-1) [   ] o.a.s.c.SolrResourceLoader using system property solr.solr.home: /opt/solr/server/solr
solr       | 1294 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter user.dir=/opt/solr/server
solr       | 1294 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter SolrDispatchFilter.init() done
solr       | 1314 INFO  (main) [   ] o.e.j.s.h.ContextHandler Started o.e.j.w.WebAppContext@3e6fa38a{/solr,file:/opt/solr/server/solr-webapp/webapp/,AVAILABLE}{/opt/solr/server/solr-webapp/webapp}
solr       | 1330 INFO  (main) [   ] o.e.j.s.ServerConnector Started ServerConnector@57cf54e1{HTTP/1.1}{0.0.0.0:8983}
solr       | 1330 INFO  (main) [   ] o.e.j.s.Server Started @1655ms
...
solr       | 1588 INFO  (coreLoadExecutor-6-thread-1) [   ] o.a.s.c.SolrConfig Using Lucene MatchVersion: 5.0.0
solr       | 1777 INFO  (coreLoadExecutor-6-thread-1) [   ] o.a.s.c.SolrConfig Loaded SolrConfig: solrconfig.xml
solr       | 1881 INFO  (coreLoadExecutor-6-thread-1) [   ] o.a.s.s.IndexSchema [foswiki] Schema name=foswiki
solr       | 2421 INFO  (coreLoadExecutor-6-thread-1) [   ] o.a.s.s.IndexSchema default search field in schema is catchall
solr       | 2422 INFO  (coreLoadExecutor-6-thread-1) [   ] o.a.s.s.IndexSchema query parser default operator is AND
solr       | 2424 INFO  (coreLoadExecutor-6-thread-1) [   ] o.a.s.s.IndexSchema unique key field: id
solr       | 2554 INFO  (coreLoadExecutor-6-thread-1) [   ] o.a.s.s.FileExchangeRateProvider Reloading exchange rates from file currency.xml
solr       | 2560 INFO  (coreLoadExecutor-6-thread-1) [   ] o.a.s.s.FileExchangeRateProvider Reloading exchange rates from file currency.xml
solr       | 2718 INFO  (coreLoadExecutor-6-thread-1) [   ] o.a.s.c.ConfigSetProperties Did not find ConfigSet properties, assuming default properties: Can't find resource 'configsetprops.json' in classpath or '/opt/solr/server/solr/configsets/foswiki_configs'
solr       | 2718 INFO  (coreLoadExecutor-6-thread-1) [   ] o.a.s.c.CoreContainer Creating SolrCore 'foswiki' using configuration from configset /opt/solr/server/solr/configsets/foswiki_configs
solr       | 2748 INFO  (coreLoadExecutor-6-thread-1) [   x:foswiki] o.a.s.c.SolrCore solr.NRTCachingDirectoryFactory
solr       | 2763 INFO  (coreLoadExecutor-6-thread-1) [   x:foswiki] o.a.s.c.SolrCore [[foswiki] ] Opening new SolrCore at [/opt/solr/server/solr/configsets/foswiki_configs], dataDir=[/opt/solr/server/solr/solr_foswiki/data/]
solr       | 2765 INFO  (coreLoadExecutor-6-thread-1) [   x:foswiki] o.a.s.c.JmxMonitoredMap No JMX servers found, not exposing Solr information with JMX.
solr       | 2768 INFO  (coreLoadExecutor-6-thread-1) [   x:foswiki] o.a.s.c.SolrCore [[foswiki] ] Added SolrEventListener for newSearcher: [org.apache.solr.core.QuerySenderListener{queries=[{q=foswiki}]}]
solr       | 2768 INFO  (coreLoadExecutor-6-thread-1) [   x:foswiki] o.a.s.c.SolrCore [[foswiki] ] Added SolrEventListener for firstSearcher: [org.apache.solr.core.QuerySenderListener{queries=[{q=foswiki}]}]
solr       | 2771 INFO  (coreLoadExecutor-6-thread-1) [   x:foswiki] o.a.s.c.SchemaCodecFactory Using default compressionMode: BEST_SPEED
solr       | 2798 ERROR (coreLoadExecutor-6-thread-1) [   x:foswiki] o.a.s.c.SolrCore :java.nio.file.AccessDeniedException: /opt/solr/server/solr/solr_foswiki/data
...
solr       | 2799 INFO  (coreLoadExecutor-6-thread-1) [   x:foswiki] o.a.s.c.SolrCore New index directory detected: old=null new=/opt/solr/server/solr/solr_foswiki/data/index/
solr       | 2800 WARN  (coreLoadExecutor-6-thread-1) [   x:foswiki] o.a.s.c.SolrCore [foswiki] Solr index directory '/opt/solr/server/solr/solr_foswiki/data/index' doesn't exist. Creating new index...
solr       | 2813 INFO  (coreLoadExecutor-6-thread-1) [   x:foswiki] o.a.s.c.SolrCore [foswiki]  CLOSING SolrCore org.apache.solr.core.SolrCore@1b62f8c4
solr       | 2814 INFO  (coreLoadExecutor-6-thread-1) [   x:foswiki] o.a.s.u.SolrCoreState Closing SolrCoreState
solr       | 2814 INFO  (coreLoadExecutor-6-thread-1) [   x:foswiki] o.a.s.u.DefaultSolrCoreState SolrCoreState ref count has reached 0 - closing IndexWriter
solr       | 2814 INFO  (coreLoadExecutor-6-thread-1) [   x:foswiki] o.a.s.c.SolrCore [foswiki] Closing main searcher on request.
solr       | 2814 INFO  (coreLoadExecutor-6-thread-1) [   x:foswiki] o.a.s.c.CachingDirectoryFactory Closing NRTCachingDirectoryFactory - 0 directories currently being tracked
solr       | 2815 ERROR (coreLoadExecutor-6-thread-1) [   x:foswiki] o.a.s.c.CoreContainer Error creating core [foswiki]: /opt/solr/server/solr/solr_foswiki/data
solr       | org.apache.solr.common.SolrException: /opt/solr/server/solr/solr_foswiki/data
...

```

I am not too much familiar with the foswiki / solr config. Any idea of whats wrong ?

**Comment by timlegge** [comment]
solr       | 2771 INFO  (coreLoadExecutor-6-thread-1) [   x:foswiki]
o.a.s.c.SchemaCodecFactory Using default compressionMode: BEST_SPEED
solr       | 2798 ERROR (coreLoadExecutor-6-thread-1) [   x:foswiki]
o.a.s.c.SolrCore :java.nio.file.AccessDeniedException:
/opt/solr/server/solr/solr_foswiki/data


Are you on RedHat with SELINUX?  Append :z to the end of the volume names


Tim

**Comment by mmallejac** [comment]
Nope. Ubuntu without SELinux. I'll give a try with :z just to be sure

Most probably a symlink issue : is the core.properties link correct from
the foswiki perspective ?

Le jeu. 14 nov. 2019 à 13:27, Timothy Legge <notifications@github.com> a
écrit :

**Comment by timlegge** [comment]
I can give your docker-compose file a shot tonight.  Will let you know

**Comment by mmallejac** [comment]
Here is an improved version of the `docker-compose.yml` file.  It uses a third container, named `setup`, which only purpose is to create the necessary symlinks at startup time (since the `command` cant be used, since it overrides the container startup command, found this method [here](https://github.com/docker/compose/issues/1510#issuecomment-505424908).

Still having problems, most probably an issue with these symlinks : solr does not have access to foswiki data : `java.nio.file.AccessDeniedException: /opt/solr/server/solr/solr_foswiki/data`

Here is the file :

```
version: '3'

services:
  foswiki:
    image: timlegge/docker-foswiki
    container_name: foswiki
    ports:
      - 8765:80
    volumes:
      - solr_logs:/opt/solr/server/logs
      - solr_configsets:/opt/solr/server/solr/configsets
      - solr_foswiki:/opt/solr/server/solr/solr_foswiki
      - foswiki_www:/var/www/foswiki
    networks:
      - foswiki-network

  setup:
    image: alpine:latest
    container_name: setup
    depends_on:
      - foswiki
    volumes:
      - solr_configsets:/opt/solr/server/solr/configsets
      - solr_foswiki:/opt/solr/server/solr/solr_foswiki
    command: sh -c "cd /opt/solr/server/solr/configsets ; [ -L foswiki_configs ] && rm foswiki_configs ; ln -s /var/www/foswiki/solr/configsets/foswiki_configs/ . ; cd /opt/solr/server/solr/solr_foswiki ; [ -L core.properties ] && rm core.properties ; ln -s /var/www/foswiki/solr/cores/foswiki/core.properties ."

  solr:
    image: solr:5
    container_name: solr
    depends_on:
      - setup
    # only usefull to have access to solr console, will be delete in production
    ports:
      - 8983:8983
    volumes:
      - solr_logs:/opt/solr/server/logs
      - solr_configsets:/opt/solr/server/solr/configsets
      - solr_foswiki:/opt/solr/server/solr/solr_foswiki
      - foswiki_www:/var/www/foswiki
    environment:
      - GC_LOG_OPTS=''
      - SOLR_LOG_LEVEL='WARN'
    networks:
      - foswiki-network

volumes:
  foswiki_www:
  solr_logs:
  solr_configsets:
  solr_foswiki:

networks:
  foswiki-network:

```

**Comment by timlegge** [comment]
Add

 ; chown -R 8983:8983 /opt/solr/server/solr

to the command in the setup

Tim

**Comment by timlegge** [comment]
A working version:

```
version: '3'

services:
  foswiki:
    image: timlegge/docker-foswiki
    container_name: foswiki
    ports:
      - 8765:80
    volumes:
      - solr_logs:/opt/solr/server/logs:z
      - solr_configsets:/opt/solr/server/solr/configsets:z
      - solr_foswiki:/opt/solr/server/solr/solr_foswiki:z
      - foswiki_www:/var/www/foswiki:z
    networks:
      - foswiki-network

  setup:
    image: alpine:latest
    container_name: setup
    depends_on:
      - foswiki
    volumes:
      - solr_configsets:/opt/solr/server/solr/configsets:z
      - solr_foswiki:/opt/solr/server/solr/solr_foswiki:z
      - foswiki_www:/var/www/foswiki:z
    command: sh -c "cd /var/www/foswiki; chown -R 8983:8983 solr; cd /opt/solr/server/solr/configsets ; [ -L foswiki_configs ] && rm foswiki_configs ; ln -s /var/www/foswiki/solr/configsets/foswiki_configs/ . ; cd /opt/solr/server/solr/solr_foswiki ; [ -L core.properties ] && rm core.properties ; ln -s /var/www/foswiki/solr/cores/foswiki/core.properties ; chown -R 8983:8983 /opt/solr/server/solr ."

  solr:
    image: solr:5
    container_name: solr
    depends_on:
      - setup
    # only usefull to have access to solr console, will be delete in production
    ports:
      - 8983:8983
    volumes:
      - solr_logs:/opt/solr/server/logs:z
      - solr_configsets:/opt/solr/server/solr/configsets:z
      - solr_foswiki:/opt/solr/server/solr/solr_foswiki:z
      - foswiki_www:/var/www/foswiki:z
    environment:
      - GC_LOG_OPTS=''
      - SOLR_LOG_LEVEL='WARN'
    networks:
      - foswiki-network

volumes:
  foswiki_www:
  solr_logs:
  solr_configsets:
  solr_foswiki:

networks:
  foswiki-network:

```
